@startuml Restaurant Reservation Use Case Diagram
actor "User" as user
rectangle "Restaurant Reservation" as RestaurantReservation {    
    usecase "Register" as register
    usecase "View\nRestaurants" as viewRestaurants
    usecase "Manage\nReservation" as manageReserv
    usecase "Manage\nRestaurant" as manageRestaurant
}

user -- register
user -- viewRestaurants
user -- manageReserv

actor "Admin" as admin
register -- admin
viewRestaurants -- admin
manageRestaurant -- admin
manageReserv -- admin

@enduml